@echo off
echo Starting FastAPI Backend...
start /B python -m uvicorn backend:app --host 0.0.0.0 --port 8000
echo Waiting for backend to initialize...
timeout /t 3 /nobreak >nul
echo Starting Streamlit Dashboard...
python -m streamlit run app.py
